-- =============================================================================
-- INSURE360 AI COPILOT — Complete Deployment Script (Single File)
-- Run as: ACCOUNTADMIN
-- =============================================================================

USE ROLE ACCOUNTADMIN;

-- =============================================================================
-- PART 1: INFRASTRUCTURE (Warehouses, Databases, Schemas)
-- =============================================================================

CREATE WAREHOUSE IF NOT EXISTS COMPUTE_WH WAREHOUSE_SIZE = 'XSMALL' AUTO_SUSPEND = 300 AUTO_RESUME = TRUE;
CREATE WAREHOUSE IF NOT EXISTS WH_INSURE360_APP WAREHOUSE_SIZE = 'XSMALL' AUTO_SUSPEND = 300 AUTO_RESUME = TRUE;

CREATE DATABASE IF NOT EXISTS INSURE360_APP;
CREATE DATABASE IF NOT EXISTS ACME_INSURANCE;

CREATE SCHEMA IF NOT EXISTS INSURE360_APP.CONFIG;
CREATE SCHEMA IF NOT EXISTS INSURE360_APP.INTERFACE;
CREATE SCHEMA IF NOT EXISTS INSURE360_APP.AI;
CREATE SCHEMA IF NOT EXISTS INSURE360_APP.ANALYTICS;
CREATE SCHEMA IF NOT EXISTS INSURE360_APP.RECOMMENDATIONS;
CREATE SCHEMA IF NOT EXISTS INSURE360_APP.GOVERNANCE;
CREATE SCHEMA IF NOT EXISTS INSURE360_APP.PIPELINE;
CREATE SCHEMA IF NOT EXISTS INSURE360_APP.SEARCH;
CREATE SCHEMA IF NOT EXISTS ACME_INSURANCE.DBO;

-- =============================================================================
-- PART 2: ROLES & GRANTS
-- =============================================================================

CREATE ROLE IF NOT EXISTS INSURE360_ADMIN;
CREATE ROLE IF NOT EXISTS INSURE360_DATA_ENGINEER;
CREATE ROLE IF NOT EXISTS INSURE360_SALES_ADVISOR;
CREATE ROLE IF NOT EXISTS INSURE360_CLAIMS_PROCESSOR;
CREATE ROLE IF NOT EXISTS INSURE360_UNDERWRITER;
CREATE ROLE IF NOT EXISTS INSURE360_RETENTION_MGR;
CREATE ROLE IF NOT EXISTS INSURE360_CC_MANAGER;
CREATE ROLE IF NOT EXISTS INSURE360_VIEWER;

GRANT ROLE INSURE360_ADMIN TO ROLE ACCOUNTADMIN;
GRANT ROLE INSURE360_DATA_ENGINEER TO ROLE INSURE360_ADMIN;
GRANT ROLE INSURE360_SALES_ADVISOR TO ROLE INSURE360_ADMIN;
GRANT ROLE INSURE360_CLAIMS_PROCESSOR TO ROLE INSURE360_ADMIN;
GRANT ROLE INSURE360_UNDERWRITER TO ROLE INSURE360_ADMIN;
GRANT ROLE INSURE360_RETENTION_MGR TO ROLE INSURE360_ADMIN;
GRANT ROLE INSURE360_CC_MANAGER TO ROLE INSURE360_ADMIN;
GRANT ROLE INSURE360_VIEWER TO ROLE INSURE360_ADMIN;

-- Warehouse grants
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE INSURE360_ADMIN;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE INSURE360_DATA_ENGINEER;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE INSURE360_SALES_ADVISOR;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE INSURE360_CLAIMS_PROCESSOR;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE INSURE360_UNDERWRITER;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE INSURE360_RETENTION_MGR;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE INSURE360_CC_MANAGER;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE INSURE360_VIEWER;
GRANT USAGE ON WAREHOUSE WH_INSURE360_APP TO ROLE INSURE360_ADMIN;

-- Database grants
GRANT USAGE ON DATABASE INSURE360_APP TO ROLE INSURE360_ADMIN;
GRANT USAGE ON DATABASE INSURE360_APP TO ROLE INSURE360_DATA_ENGINEER;
GRANT USAGE ON DATABASE INSURE360_APP TO ROLE INSURE360_SALES_ADVISOR;
GRANT USAGE ON DATABASE INSURE360_APP TO ROLE INSURE360_CLAIMS_PROCESSOR;
GRANT USAGE ON DATABASE INSURE360_APP TO ROLE INSURE360_UNDERWRITER;
GRANT USAGE ON DATABASE INSURE360_APP TO ROLE INSURE360_RETENTION_MGR;
GRANT USAGE ON DATABASE INSURE360_APP TO ROLE INSURE360_CC_MANAGER;
GRANT USAGE ON DATABASE INSURE360_APP TO ROLE INSURE360_VIEWER;
GRANT USAGE ON DATABASE ACME_INSURANCE TO ROLE INSURE360_ADMIN;

-- Schema grants
GRANT USAGE ON ALL SCHEMAS IN DATABASE INSURE360_APP TO ROLE INSURE360_ADMIN;
GRANT USAGE ON ALL SCHEMAS IN DATABASE INSURE360_APP TO ROLE INSURE360_DATA_ENGINEER;
GRANT USAGE ON ALL SCHEMAS IN DATABASE INSURE360_APP TO ROLE INSURE360_SALES_ADVISOR;
GRANT USAGE ON ALL SCHEMAS IN DATABASE INSURE360_APP TO ROLE INSURE360_CLAIMS_PROCESSOR;
GRANT USAGE ON ALL SCHEMAS IN DATABASE INSURE360_APP TO ROLE INSURE360_UNDERWRITER;
GRANT USAGE ON ALL SCHEMAS IN DATABASE INSURE360_APP TO ROLE INSURE360_RETENTION_MGR;
GRANT USAGE ON ALL SCHEMAS IN DATABASE INSURE360_APP TO ROLE INSURE360_CC_MANAGER;
GRANT USAGE ON ALL SCHEMAS IN DATABASE INSURE360_APP TO ROLE INSURE360_VIEWER;
GRANT USAGE ON SCHEMA ACME_INSURANCE.DBO TO ROLE INSURE360_ADMIN;

-- Ownership
GRANT OWNERSHIP ON SCHEMA INSURE360_APP.INTERFACE TO ROLE INSURE360_ADMIN COPY CURRENT GRANTS;
GRANT OWNERSHIP ON SCHEMA INSURE360_APP.CONFIG TO ROLE INSURE360_ADMIN COPY CURRENT GRANTS;
GRANT OWNERSHIP ON SCHEMA INSURE360_APP.AI TO ROLE INSURE360_ADMIN COPY CURRENT GRANTS;
GRANT OWNERSHIP ON SCHEMA INSURE360_APP.ANALYTICS TO ROLE INSURE360_ADMIN COPY CURRENT GRANTS;
GRANT OWNERSHIP ON SCHEMA INSURE360_APP.RECOMMENDATIONS TO ROLE INSURE360_ADMIN COPY CURRENT GRANTS;
GRANT OWNERSHIP ON SCHEMA INSURE360_APP.GOVERNANCE TO ROLE INSURE360_ADMIN COPY CURRENT GRANTS;

-- =============================================================================
-- PART 3: ACME SOURCE TABLES (Sample Insurance Company)
-- =============================================================================

USE DATABASE ACME_INSURANCE;
USE SCHEMA DBO;

CREATE OR REPLACE TABLE TBL_CLIENTS (
    CLIENTID NUMBER(38,0), FNAME VARCHAR(100), LNAME VARCHAR(100), DOB DATE,
    SEX VARCHAR(1), PANCARD VARCHAR(10), AADHAARNO VARCHAR(12), PHONENO VARCHAR(15),
    EMAILID VARCHAR(200), ADDR VARCHAR(500), CITYNAME VARCHAR(100), STATENAME VARCHAR(100),
    ZIP VARCHAR(10), TIER VARCHAR(1), JOINDT DATE, KYCDONE VARCHAR(1),
    SALARY NUMBER(15,2), JOB VARCHAR(100), MARSTATUS VARCHAR(1),
    DEPENDENTS NUMBER(38,0), ACTIVEFLG NUMBER(38,0)
);

CREATE OR REPLACE TABLE TBL_POLICYMASTER (
    POLID VARCHAR(50), CLIENTID NUMBER(38,0), LOB VARCHAR(5), PRODNAME VARCHAR(200),
    STARTDT DATE, ENDDT DATE, SUMASSURED NUMBER(15,2), PREM NUMBER(12,2),
    PREMFREQ VARCHAR(1), POLSTATUS VARCHAR(5), UWSTATUS VARCHAR(5), RISKCAT VARCHAR(1),
    RISKPCT NUMBER(5,2), AGENTCODE VARCHAR(20), BRANCHID VARCHAR(20), ISRENEW NUMBER(38,0)
);

CREATE OR REPLACE TABLE TBL_CLAIMREGISTER (
    CLAIMNO VARCHAR(50), POLID VARCHAR(50), CLIENTID NUMBER(38,0), CLAIMDT DATE,
    CLAIMTYP VARCHAR(5), CLAIMCAT VARCHAR(5), AMTCLAIMED NUMBER(12,2), AMTAPPROVED NUMBER(12,2),
    STATUS VARCHAR(5), CAUSEOFLOSS VARCHAR(500), SETTLEDT DATE, DIAGDESC VARCHAR(1000),
    TREATTYPE VARCHAR(100), FRAUDYN VARCHAR(1), FRAUDPCT NUMBER(5,2),
    CLAIMNOTES VARCHAR(2000), PRIORITY VARCHAR(1), SLABREACH NUMBER(38,0)
);

CREATE OR REPLACE TABLE TBL_INTERACTIONS (
    INTID VARCHAR(50), CLIENTID NUMBER(38,0), INTDATE TIMESTAMP_NTZ, CHANNEL VARCHAR(20),
    DIRECTION VARCHAR(20), INTTYPE VARCHAR(30), SUBJECT VARCHAR(500), SUMMARY VARCHAR(2000),
    RESOLUTION VARCHAR(30), AGENTCODE VARCHAR(20), HANDLESECS NUMBER(38,0),
    CSATSCORE NUMBER(3,1), RELPOLID VARCHAR(50), RELCLMID VARCHAR(50)
);

CREATE OR REPLACE TABLE TBL_TRANSCRIPTS (
    TRANSID VARCHAR(50), CLIENTID NUMBER(38,0), INTID VARCHAR(50),
    TRANSTEXT VARCHAR(16777216), LANG VARCHAR(50), CALLTS TIMESTAMP_NTZ
);

CREATE OR REPLACE TABLE TBL_EMAILS (
    EMAILID VARCHAR(50), CLIENTID NUMBER(38,0), DIRECTION VARCHAR(20),
    FROMADDR VARCHAR(200), TOADDR VARCHAR(200), SUBJECT VARCHAR(500),
    BODYTEXT VARCHAR(16777216), EMAILTS TIMESTAMP_NTZ
);

GRANT SELECT ON ALL TABLES IN SCHEMA ACME_INSURANCE.DBO TO ROLE INSURE360_ADMIN;
GRANT SELECT ON FUTURE TABLES IN SCHEMA ACME_INSURANCE.DBO TO ROLE INSURE360_ADMIN;

-- =============================================================================
-- PART 4: LOAD SAMPLE DATA
-- After running this script, load CSV data into ACME tables:
--
--   CREATE STAGE IF NOT EXISTS ACME_INSURANCE.DBO.DATA_STAGE;
--   -- Upload CSVs via Snowsight UI or PUT command, then:
--   COPY INTO TBL_CLIENTS FROM @DATA_STAGE/tbl_clients.csv FILE_FORMAT=(TYPE=CSV SKIP_HEADER=1 FIELD_OPTIONALLY_ENCLOSED_BY='"');
--   COPY INTO TBL_POLICYMASTER FROM @DATA_STAGE/tbl_policymaster.csv FILE_FORMAT=(TYPE=CSV SKIP_HEADER=1 FIELD_OPTIONALLY_ENCLOSED_BY='"');
--   COPY INTO TBL_CLAIMREGISTER FROM @DATA_STAGE/tbl_claimregister.csv FILE_FORMAT=(TYPE=CSV SKIP_HEADER=1 FIELD_OPTIONALLY_ENCLOSED_BY='"');
--   COPY INTO TBL_INTERACTIONS FROM @DATA_STAGE/tbl_interactions.csv FILE_FORMAT=(TYPE=CSV SKIP_HEADER=1 FIELD_OPTIONALLY_ENCLOSED_BY='"');
--   COPY INTO TBL_TRANSCRIPTS FROM @DATA_STAGE/tbl_transcripts.csv FILE_FORMAT=(TYPE=CSV SKIP_HEADER=1 FIELD_OPTIONALLY_ENCLOSED_BY='"');
--   COPY INTO TBL_EMAILS FROM @DATA_STAGE/tbl_emails.csv FILE_FORMAT=(TYPE=CSV SKIP_HEADER=1 FIELD_OPTIONALLY_ENCLOSED_BY='"');
-- =============================================================================


-- =============================================================================
-- PART 5: CONFIG TABLES
-- =============================================================================

USE DATABASE INSURE360_APP;

CREATE TABLE IF NOT EXISTS CONFIG.INTERFACE_CONTRACTS (
    INTERFACE_NAME VARCHAR(100) NOT NULL, COLUMN_NAME VARCHAR(100) NOT NULL,
    DATA_TYPE VARCHAR(50) NOT NULL, IS_REQUIRED BOOLEAN DEFAULT FALSE,
    IS_PII BOOLEAN DEFAULT FALSE, COLUMN_ORDER NUMBER(38,0),
    DESCRIPTION VARCHAR(500), DEFAULT_EXPRESSION VARCHAR(500),
    PRIMARY KEY (INTERFACE_NAME, COLUMN_NAME)
);

CREATE TABLE IF NOT EXISTS CONFIG.SOURCE_TABLE_MAPPING (
    MAPPING_ID NUMBER(38,0) AUTOINCREMENT, INTERFACE_NAME VARCHAR(100) NOT NULL,
    SOURCE_DATABASE VARCHAR(100) NOT NULL, SOURCE_SCHEMA VARCHAR(100) NOT NULL,
    SOURCE_TABLE VARCHAR(100) NOT NULL, JOIN_TYPE VARCHAR(20) DEFAULT 'BASE',
    JOIN_CONDITION VARCHAR(500), JOIN_ORDER NUMBER(38,0) DEFAULT 0,
    SOURCE_FILTER VARCHAR(500), IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CREATED_BY VARCHAR(100) DEFAULT CURRENT_USER(), PRIMARY KEY (MAPPING_ID)
);

CREATE TABLE IF NOT EXISTS CONFIG.COLUMN_MAPPING (
    COLUMN_MAPPING_ID NUMBER(38,0) AUTOINCREMENT, INTERFACE_NAME VARCHAR(100) NOT NULL,
    INTERFACE_COLUMN VARCHAR(100) NOT NULL, SOURCE_EXPRESSION VARCHAR(500) NOT NULL,
    DATA_TYPE VARCHAR(50), TRANSFORMATION_NOTES VARCHAR(500),
    IS_ACTIVE BOOLEAN DEFAULT TRUE, CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (COLUMN_MAPPING_ID)
);

CREATE TABLE IF NOT EXISTS CONFIG.VALUE_MAPPING (
    VALUE_MAPPING_ID NUMBER(38,0) AUTOINCREMENT, INTERFACE_NAME VARCHAR(100) NOT NULL,
    INTERFACE_COLUMN VARCHAR(100) NOT NULL, SOURCE_VALUE VARCHAR(100),
    TARGET_VALUE VARCHAR(200) NOT NULL, IS_DEFAULT BOOLEAN DEFAULT FALSE,
    IS_ACTIVE BOOLEAN DEFAULT TRUE, PRIMARY KEY (VALUE_MAPPING_ID)
);

CREATE TABLE IF NOT EXISTS CONFIG.ONBOARDING_STATUS (
    INTERFACE_NAME VARCHAR(100) PRIMARY KEY, MAPPING_STATUS VARCHAR(20) DEFAULT 'PENDING',
    LAST_GENERATED_AT TIMESTAMP_NTZ, ROW_COUNT NUMBER(38,0), VALIDATION_ERRORS VARIANT,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS CONFIG.ROLE_PAGE_ACCESS (
    ROLE_NAME VARCHAR(100) NOT NULL, PAGE_KEY VARCHAR(50) NOT NULL,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CREATED_BY VARCHAR(100) DEFAULT CURRENT_USER(),
    PRIMARY KEY (ROLE_NAME, PAGE_KEY)
);

CREATE TABLE IF NOT EXISTS CONFIG.ROLE_MAPPING (
    MAPPING_ID NUMBER(38,0) AUTOINCREMENT, SOURCE_ROLE VARCHAR(100) NOT NULL,
    INSURE360_ROLE VARCHAR(100) NOT NULL, IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CREATED_BY VARCHAR(100) DEFAULT CURRENT_USER(), DESCRIPTION VARCHAR(500),
    PRIORITY NUMBER(38,0) DEFAULT 1, PRIMARY KEY (MAPPING_ID)
);

-- Seed role-page access
INSERT INTO CONFIG.ROLE_PAGE_ACCESS (ROLE_NAME, PAGE_KEY) VALUES
('ACCOUNTADMIN','executive_dashboard'),('ACCOUNTADMIN','customer_360'),
('ACCOUNTADMIN','claims_intelligence'),('ACCOUNTADMIN','recommendations'),
('ACCOUNTADMIN','integration_config'),('ACCOUNTADMIN','role_config'),
('INSURE360_ADMIN','executive_dashboard'),('INSURE360_ADMIN','customer_360'),
('INSURE360_ADMIN','claims_intelligence'),('INSURE360_ADMIN','recommendations'),
('INSURE360_ADMIN','integration_config'),('INSURE360_ADMIN','role_config'),
('INSURE360_DATA_ENGINEER','executive_dashboard'),('INSURE360_DATA_ENGINEER','customer_360'),
('INSURE360_DATA_ENGINEER','claims_intelligence'),('INSURE360_DATA_ENGINEER','recommendations'),
('INSURE360_DATA_ENGINEER','integration_config'),
('INSURE360_SALES_ADVISOR','executive_dashboard'),('INSURE360_SALES_ADVISOR','customer_360'),
('INSURE360_SALES_ADVISOR','recommendations'),
('INSURE360_CLAIMS_PROCESSOR','customer_360'),('INSURE360_CLAIMS_PROCESSOR','claims_intelligence'),
('INSURE360_UNDERWRITER','executive_dashboard'),('INSURE360_UNDERWRITER','customer_360'),
('INSURE360_UNDERWRITER','claims_intelligence'),
('INSURE360_RETENTION_MGR','executive_dashboard'),('INSURE360_RETENTION_MGR','customer_360'),
('INSURE360_RETENTION_MGR','recommendations'),
('INSURE360_CC_MANAGER','executive_dashboard'),('INSURE360_CC_MANAGER','customer_360'),
('INSURE360_VIEWER','executive_dashboard');


-- =============================================================================
-- PART 6: AI TABLES & RECOMMENDATION TABLES
-- =============================================================================

CREATE TABLE IF NOT EXISTS AI.AI_INSIGHTS (
    INSIGHT_ID VARCHAR(100) PRIMARY KEY, CUSTOMER_ID VARCHAR(50) NOT NULL,
    SOURCE_TYPE VARCHAR(30), SOURCE_ID VARCHAR(100), PROCESSING_DATE TIMESTAMP_NTZ,
    SUMMARY VARCHAR(16777216), PRIMARY_INTENT VARCHAR(50), SECONDARY_INTENT VARCHAR(50),
    INTENT_CONFIDENCE NUMBER(5,4), SENTIMENT_LABEL VARCHAR(20), SENTIMENT_SCORE NUMBER(5,4),
    ENTITIES_EXTRACTED VARIANT, LIFE_EVENT_DETECTED VARCHAR(50),
    LIFE_EVENT_CONFIDENCE NUMBER(5,4), LIFE_EVENT_EVIDENCE VARCHAR(500),
    MODEL_USED VARCHAR(50), PROCESSING_TIME_MS NUMBER(38,0), TOKEN_COUNT NUMBER(38,0),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS AI.LIFE_EVENTS (
    EVENT_ID VARCHAR(100) PRIMARY KEY, CUSTOMER_ID VARCHAR(50) NOT NULL,
    EVENT_TYPE VARCHAR(50) NOT NULL, DETECTION_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CONFIDENCE_SCORE NUMBER(5,4), SOURCE_TYPE VARCHAR(30), SOURCE_ID VARCHAR(100),
    EVIDENCE_TEXT VARCHAR(1000), STATUS VARCHAR(20) DEFAULT 'DETECTED',
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS RECOMMENDATIONS.NEXT_BEST_ACTION (
    RECOMMENDATION_ID VARCHAR(50) PRIMARY KEY, CUSTOMER_ID VARCHAR(50) NOT NULL,
    RECOMMENDATION_DATE TIMESTAMP_NTZ NOT NULL, ACTION_TYPE VARCHAR(30) NOT NULL,
    RECOMMENDATION VARCHAR(500) NOT NULL, RECOMMENDATION_DETAIL VARCHAR(16777216),
    PRODUCT_RECOMMENDED VARCHAR(100), CONFIDENCE_SCORE NUMBER(5,4) NOT NULL,
    PRIORITY_RANK NUMBER(38,0), REASONING VARCHAR(16777216) NOT NULL,
    REASONING_FACTORS VARIANT, LLM_REASONING VARCHAR(16777216),
    BUSINESS_IMPACT VARCHAR(20), EXPECTED_REVENUE NUMBER(12,2),
    EXPECTED_RETENTION_LIFT NUMBER(5,2), RISK_IF_NOT_ACTED VARCHAR(500),
    STATUS VARCHAR(20) DEFAULT 'GENERATED', ASSIGNED_TO_ROLE VARCHAR(50),
    ACTIONED_DATE TIMESTAMP_NTZ, ACTION_OUTCOME VARCHAR(50),
    TRIGGER_EVENT VARCHAR(100), MODEL_VERSION VARCHAR(20), BATCH_ID VARCHAR(50),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS RECOMMENDATIONS.TICKETS (
    TICKET_ID VARCHAR(20) PRIMARY KEY, RECOMMENDATION_ID VARCHAR(50) NOT NULL,
    CUSTOMER_ID VARCHAR(50) NOT NULL, CUSTOMER_NAME VARCHAR(200),
    ACTION_TYPE VARCHAR(30), RECOMMENDATION VARCHAR(500), PRIORITY VARCHAR(20),
    DEPARTMENT VARCHAR(50), REASONING VARCHAR(16777216), CONFIDENCE_SCORE NUMBER(5,4),
    ASSIGNED_TO_ROLE VARCHAR(50) DEFAULT 'INSURE360_ADMIN',
    STATUS VARCHAR(20) DEFAULT 'OPEN', CREATED_BY VARCHAR(100),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(), UPDATED_AT TIMESTAMP_NTZ,
    RESOLVED_BY VARCHAR(100), RESOLVED_AT TIMESTAMP_NTZ,
    RESOLUTION_NOTES VARCHAR(16777216), RESOLVE_COMMENTS VARCHAR(16777216)
);

CREATE SEQUENCE IF NOT EXISTS RECOMMENDATIONS.SEQ_TICKET_ID START = 10001 INCREMENT = 1;


-- =============================================================================
-- PART 7: AI UDFs (Cortex AI - llama3.1-70b)
-- =============================================================================

CREATE OR REPLACE FUNCTION AI.SUMMARIZE_TRANSCRIPT(TRANSCRIPT VARCHAR)
RETURNS VARCHAR LANGUAGE SQL AS $$
    SNOWFLAKE.CORTEX.COMPLETE('llama3.1-70b',
        CONCAT('You are an insurance call center analyst. Summarize the following customer call transcript in 3-5 bullet points. Focus on: (1) reason for call, (2) key issues raised, (3) resolution or pending actions, (4) customer sentiment. Be concise.\n\nTRANSCRIPT:\n', transcript, '\n\nSUMMARY:'))
$$;

CREATE OR REPLACE FUNCTION AI.ANALYZE_SENTIMENT(INTERACTION_TEXT VARCHAR)
RETURNS VARIANT LANGUAGE SQL AS $$
    PARSE_JSON(SNOWFLAKE.CORTEX.COMPLETE('llama3.1-70b',
        CONCAT('Analyze sentiment of this insurance interaction.\nReturn JSON: {"sentiment_label":"POSITIVE/NEGATIVE/NEUTRAL/MIXED","sentiment_score":-1.0 to 1.0,"urgency":"LOW/MEDIUM/HIGH"}\n\nTEXT:\n', interaction_text, '\n\nReturn ONLY the JSON.')))
$$;

CREATE OR REPLACE FUNCTION AI.DETECT_INTENT(INTERACTION_TEXT VARCHAR)
RETURNS VARIANT LANGUAGE SQL AS $$
    PARSE_JSON(SNOWFLAKE.CORTEX.COMPLETE('llama3.1-70b',
        CONCAT('You are an insurance NLP specialist. Detect the intent from this interaction.\nReturn JSON: {"primary_intent":"<one of: CLAIM_INQUIRY,CLAIM_FILING,POLICY_RENEWAL,POLICY_CANCELLATION,PREMIUM_PAYMENT,COVERAGE_QUESTION,COMPLAINT,FEEDBACK,NEW_POLICY_INQUIRY,GENERAL_INQUIRY>","confidence":0.0-1.0,"urgency":"LOW/MEDIUM/HIGH"}\n\nTEXT:\n', interaction_text, '\n\nReturn ONLY the JSON.')))
$$;

CREATE OR REPLACE FUNCTION AI.DETECT_LIFE_EVENT(INTERACTION_TEXT VARCHAR)
RETURNS VARIANT LANGUAGE SQL AS $$
    PARSE_JSON(SNOWFLAKE.CORTEX.COMPLETE('llama3.1-70b',
        CONCAT('Detect life events from this insurance interaction.\nEvents: MARRIAGE, NEW_CHILD, HOME_PURCHASE, VEHICLE_PURCHASE, RETIREMENT_PLANNING, BUSINESS_STARTUP, MEDICAL_EVENT\nReturn JSON: {"life_event_detected":"<TYPE or NONE>","confidence":0.0-1.0,"evidence":"<phrase>"}\n\nTEXT:\n', interaction_text, '\n\nReturn ONLY the JSON.')))
$$;

CREATE OR REPLACE FUNCTION AI.EXTRACT_ENTITIES(INTERACTION_TEXT VARCHAR)
RETURNS VARIANT LANGUAGE SQL AS $$
    PARSE_JSON(SNOWFLAKE.CORTEX.COMPLETE('llama3.1-70b',
        CONCAT('Extract insurance entities from this text.\nReturn JSON: {"policy_numbers":[],"claim_numbers":[],"person_names":[],"amounts":[]}\n\nTEXT:\n', interaction_text, '\n\nReturn ONLY the JSON.')))
$$;

CREATE OR REPLACE FUNCTION AI.GENERATE_NBA(CUSTOMER_360_DATA VARIANT)
RETURNS VARIANT LANGUAGE SQL AS $$
    PARSE_JSON(
        REPLACE(REPLACE(REPLACE(
            SNOWFLAKE.CORTEX.COMPLETE('llama3.1-70b',
                CONCAT('Return a JSON array of 3 insurance recommendations for this customer. Each item: {"action":"CROSS_SELL/UPSELL/RETAIN/SERVICE","text":"short recommendation","product":"product name or null","score":0.8,"impact":"HIGH/MEDIUM/LOW","revenue":10000,"reason":"one sentence"}.
Reply ONLY with a JSON array [...]. No markdown.

Customer: ', TO_VARCHAR(customer_360_data))
            ),
            '```json', ''
        ), '```', ''), CHR(10), ' ')
    )
$$;


-- =============================================================================
-- PART 8: MASKING POLICIES
-- =============================================================================

CREATE OR REPLACE MASKING POLICY GOVERNANCE.MASK_PAN_NUMBER AS (VAL VARCHAR)
RETURNS VARCHAR ->
CASE WHEN CURRENT_ROLE() IN ('ACCOUNTADMIN','INSURE360_ADMIN','INSURE360_UNDERWRITER') THEN val
     WHEN val IS NOT NULL THEN CONCAT('XXXXXX', RIGHT(val, 4))
     ELSE NULL END;

CREATE OR REPLACE MASKING POLICY GOVERNANCE.MASK_AADHAAR_NUMBER AS (VAL VARCHAR)
RETURNS VARCHAR ->
CASE WHEN CURRENT_ROLE() IN ('ACCOUNTADMIN','INSURE360_ADMIN') THEN val
     WHEN val IS NOT NULL THEN CONCAT('XXXX-XXXX-', RIGHT(val, 4))
     ELSE NULL END;

CREATE OR REPLACE MASKING POLICY GOVERNANCE.MASK_MOBILE_NUMBER AS (VAL VARCHAR)
RETURNS VARCHAR ->
CASE WHEN CURRENT_ROLE() IN ('ACCOUNTADMIN','INSURE360_ADMIN','INSURE360_CC_MANAGER','INSURE360_SALES_ADVISOR') THEN val
     WHEN val IS NOT NULL THEN CONCAT('+XX-XXXXX-', RIGHT(val, 4))
     ELSE NULL END;

CREATE OR REPLACE MASKING POLICY GOVERNANCE.MASK_EMAIL_ADDRESS AS (VAL VARCHAR)
RETURNS VARCHAR ->
CASE WHEN CURRENT_ROLE() IN ('ACCOUNTADMIN','INSURE360_ADMIN','INSURE360_CC_MANAGER','INSURE360_SALES_ADVISOR') THEN val
     WHEN val IS NOT NULL AND CHARINDEX('@', val) > 0 THEN CONCAT('****@', SPLIT_PART(val, '@', 2))
     ELSE '****@****.***' END;

CREATE OR REPLACE MASKING POLICY GOVERNANCE.MASK_MEDICAL_INFO AS (VAL VARCHAR)
RETURNS VARCHAR ->
CASE WHEN CURRENT_ROLE() IN ('ACCOUNTADMIN','INSURE360_ADMIN','INSURE360_UNDERWRITER','INSURE360_CLAIMS_PROCESSOR') THEN val
     ELSE '*** MEDICAL DATA RESTRICTED ***' END;


-- =============================================================================
-- PART 9: STORED PROCEDURE (Mapping Engine)
-- =============================================================================

CREATE OR REPLACE PROCEDURE CONFIG.GENERATE_INTERFACE_VIEW(P_INTERFACE_NAME VARCHAR)
RETURNS VARCHAR LANGUAGE SQL EXECUTE AS CALLER
AS
$$
DECLARE
    v_iface VARCHAR DEFAULT P_INTERFACE_NAME;
    v_sql TEXT; v_select_list TEXT DEFAULT ''; v_from_clause TEXT DEFAULT '';
    v_base_table TEXT; v_base_filter TEXT; v_has_value_map INT;
    v_value_case TEXT; v_col_name VARCHAR; v_col_expr VARCHAR; v_col_default VARCHAR;
    cur_columns CURSOR FOR
        SELECT ic.COLUMN_NAME, ic.DEFAULT_EXPRESSION, cm.SOURCE_EXPRESSION
        FROM INSURE360_APP.CONFIG.INTERFACE_CONTRACTS ic
        LEFT JOIN INSURE360_APP.CONFIG.COLUMN_MAPPING cm
            ON ic.INTERFACE_NAME = cm.INTERFACE_NAME AND ic.COLUMN_NAME = cm.INTERFACE_COLUMN AND cm.IS_ACTIVE = TRUE
        WHERE ic.INTERFACE_NAME = ? ORDER BY ic.COLUMN_ORDER;
BEGIN
    SELECT CONCAT(SOURCE_DATABASE, '.', SOURCE_SCHEMA, '.', SOURCE_TABLE), SOURCE_FILTER
    INTO :v_base_table, :v_base_filter
    FROM INSURE360_APP.CONFIG.SOURCE_TABLE_MAPPING
    WHERE INTERFACE_NAME = :v_iface AND IS_ACTIVE = TRUE AND JOIN_ORDER = 0 LIMIT 1;
    IF (v_base_table IS NULL) THEN RETURN CONCAT('ERROR: No base table mapped for ', :v_iface); END IF;
    v_from_clause := CONCAT(v_base_table, ' T0');
    OPEN cur_columns USING (:v_iface);
    FOR col_rec IN cur_columns DO
        v_col_name := col_rec.COLUMN_NAME; v_col_expr := col_rec.SOURCE_EXPRESSION; v_col_default := col_rec.DEFAULT_EXPRESSION;
        LET final_expr TEXT;
        IF (v_col_expr IS NOT NULL) THEN
            final_expr := v_col_expr;
            SELECT COUNT(*) INTO :v_has_value_map FROM INSURE360_APP.CONFIG.VALUE_MAPPING WHERE INTERFACE_NAME = :v_iface AND INTERFACE_COLUMN = :v_col_name;
            IF (v_has_value_map > 0) THEN
                SELECT LISTAGG(CASE WHEN IS_DEFAULT THEN CONCAT(' ELSE ''', TARGET_VALUE, '''') ELSE CONCAT(' WHEN ''', SOURCE_VALUE, ''' THEN ''', TARGET_VALUE, '''') END, '') WITHIN GROUP (ORDER BY IS_DEFAULT) INTO :v_value_case FROM INSURE360_APP.CONFIG.VALUE_MAPPING WHERE INTERFACE_NAME = :v_iface AND INTERFACE_COLUMN = :v_col_name;
                final_expr := CONCAT('CASE ', final_expr, v_value_case, ' END');
            END IF;
        ELSEIF (v_col_default IS NOT NULL) THEN final_expr := v_col_default;
        ELSE final_expr := 'NULL'; END IF;
        IF (LENGTH(v_select_list) > 0) THEN v_select_list := CONCAT(v_select_list, ', '); END IF;
        v_select_list := CONCAT(v_select_list, final_expr, ' AS ', v_col_name);
    END FOR;
    IF (v_base_filter IS NOT NULL AND LENGTH(v_base_filter) > 0) THEN
        v_sql := CONCAT('CREATE OR REPLACE VIEW INSURE360_APP.INTERFACE.', :v_iface, ' AS SELECT ', v_select_list, ' FROM ', v_from_clause, ' WHERE ', v_base_filter);
    ELSE
        v_sql := CONCAT('CREATE OR REPLACE VIEW INSURE360_APP.INTERFACE.', :v_iface, ' AS SELECT ', v_select_list, ' FROM ', v_from_clause);
    END IF;
    EXECUTE IMMEDIATE v_sql;
    UPDATE INSURE360_APP.CONFIG.ONBOARDING_STATUS SET MAPPING_STATUS = 'ACTIVE', LAST_GENERATED_AT = CURRENT_TIMESTAMP(), UPDATED_AT = CURRENT_TIMESTAMP() WHERE INTERFACE_NAME = :v_iface;
    RETURN CONCAT('SUCCESS: INSURE360_APP.INTERFACE.', :v_iface);
END;
$$;


-- =============================================================================
-- PART 10: ACME INSURANCE MAPPING (Contracts + Column Maps + Value Maps)
-- =============================================================================

-- Interface Contracts
INSERT INTO CONFIG.INTERFACE_CONTRACTS (INTERFACE_NAME, COLUMN_NAME, DATA_TYPE, IS_REQUIRED, IS_PII, COLUMN_ORDER, DESCRIPTION) VALUES
('V_CUSTOMERS','CUSTOMER_ID','VARCHAR',TRUE,FALSE,1,'Unique customer ID'),('V_CUSTOMERS','FIRST_NAME','VARCHAR',TRUE,TRUE,2,'First name'),
('V_CUSTOMERS','LAST_NAME','VARCHAR',TRUE,TRUE,3,'Last name'),('V_CUSTOMERS','DATE_OF_BIRTH','DATE',FALSE,TRUE,4,'DOB'),
('V_CUSTOMERS','GENDER','VARCHAR',FALSE,FALSE,5,'Gender'),('V_CUSTOMERS','PAN_NUMBER','VARCHAR',FALSE,TRUE,6,'PAN'),
('V_CUSTOMERS','AADHAAR_NUMBER','VARCHAR',FALSE,TRUE,7,'Aadhaar'),('V_CUSTOMERS','MOBILE_NUMBER','VARCHAR',FALSE,TRUE,8,'Mobile'),
('V_CUSTOMERS','EMAIL_ADDRESS','VARCHAR',FALSE,TRUE,9,'Email'),('V_CUSTOMERS','ADDRESS_LINE_1','VARCHAR',FALSE,TRUE,10,'Address'),
('V_CUSTOMERS','CITY','VARCHAR',FALSE,FALSE,11,'City'),('V_CUSTOMERS','STATE','VARCHAR',FALSE,FALSE,12,'State'),
('V_CUSTOMERS','PINCODE','VARCHAR',FALSE,FALSE,13,'PIN'),('V_CUSTOMERS','COUNTRY','VARCHAR',FALSE,FALSE,14,'Country'),
('V_CUSTOMERS','CUSTOMER_SEGMENT','VARCHAR',FALSE,FALSE,15,'Segment'),('V_CUSTOMERS','CUSTOMER_TYPE','VARCHAR',FALSE,FALSE,16,'Type'),
('V_CUSTOMERS','ONBOARDING_DATE','DATE',FALSE,FALSE,17,'Join date'),('V_CUSTOMERS','KYC_STATUS','VARCHAR',FALSE,FALSE,18,'KYC'),
('V_CUSTOMERS','ANNUAL_INCOME','NUMBER',FALSE,FALSE,19,'Income'),('V_CUSTOMERS','OCCUPATION','VARCHAR',FALSE,FALSE,20,'Occupation'),
('V_CUSTOMERS','MARITAL_STATUS','VARCHAR',FALSE,FALSE,21,'Marital'),('V_CUSTOMERS','NUMBER_OF_DEPENDENTS','NUMBER',FALSE,FALSE,22,'Dependents'),
('V_CUSTOMERS','PREFERRED_CHANNEL','VARCHAR',FALSE,FALSE,23,'Channel'),('V_CUSTOMERS','IS_ACTIVE','BOOLEAN',FALSE,FALSE,24,'Active');

INSERT INTO CONFIG.INTERFACE_CONTRACTS (INTERFACE_NAME, COLUMN_NAME, DATA_TYPE, IS_REQUIRED, IS_PII, COLUMN_ORDER) VALUES
('V_POLICIES','POLICY_ID','VARCHAR',TRUE,FALSE,1),('V_POLICIES','CUSTOMER_ID','VARCHAR',TRUE,FALSE,2),
('V_POLICIES','POLICY_TYPE','VARCHAR',TRUE,FALSE,3),('V_POLICIES','PRODUCT_NAME','VARCHAR',FALSE,FALSE,4),
('V_POLICIES','INCEPTION_DATE','DATE',FALSE,FALSE,5),('V_POLICIES','EXPIRY_DATE','DATE',FALSE,FALSE,6),
('V_POLICIES','SUM_INSURED','NUMBER',FALSE,FALSE,7),('V_POLICIES','ANNUAL_PREMIUM','NUMBER',FALSE,FALSE,8),
('V_POLICIES','PREMIUM_FREQUENCY','VARCHAR',FALSE,FALSE,9),('V_POLICIES','POLICY_STATUS','VARCHAR',FALSE,FALSE,10),
('V_POLICIES','UNDERWRITING_STATUS','VARCHAR',FALSE,FALSE,11),('V_POLICIES','RISK_CATEGORY','VARCHAR',FALSE,FALSE,12),
('V_POLICIES','RISK_SCORE','NUMBER',FALSE,FALSE,13),('V_POLICIES','AGENT_ID','VARCHAR',FALSE,FALSE,14),
('V_POLICIES','BRANCH_CODE','VARCHAR',FALSE,FALSE,15),('V_POLICIES','IS_RENEWAL','BOOLEAN',FALSE,FALSE,16);

INSERT INTO CONFIG.INTERFACE_CONTRACTS (INTERFACE_NAME, COLUMN_NAME, DATA_TYPE, IS_REQUIRED, IS_PII, COLUMN_ORDER) VALUES
('V_CLAIMS','CLAIM_ID','VARCHAR',TRUE,FALSE,1),('V_CLAIMS','POLICY_ID','VARCHAR',TRUE,FALSE,2),
('V_CLAIMS','CUSTOMER_ID','VARCHAR',TRUE,FALSE,3),('V_CLAIMS','CLAIM_DATE','DATE',FALSE,FALSE,4),
('V_CLAIMS','CLAIM_TYPE','VARCHAR',FALSE,FALSE,5),('V_CLAIMS','CLAIM_CATEGORY','VARCHAR',FALSE,FALSE,6),
('V_CLAIMS','CLAIM_AMOUNT','NUMBER',FALSE,FALSE,7),('V_CLAIMS','APPROVED_AMOUNT','NUMBER',FALSE,FALSE,8),
('V_CLAIMS','CLAIM_STATUS','VARCHAR',FALSE,FALSE,9),('V_CLAIMS','CAUSE_OF_LOSS','VARCHAR',FALSE,FALSE,10),
('V_CLAIMS','SETTLEMENT_DATE','DATE',FALSE,FALSE,11),('V_CLAIMS','DIAGNOSIS_DESCRIPTION','VARCHAR',FALSE,TRUE,12),
('V_CLAIMS','TREATMENT_TYPE','VARCHAR',FALSE,TRUE,13),('V_CLAIMS','FRAUD_FLAG','VARCHAR',FALSE,FALSE,14),
('V_CLAIMS','FRAUD_SCORE','NUMBER',FALSE,FALSE,15),('V_CLAIMS','CLAIM_DESCRIPTION','VARCHAR',FALSE,FALSE,16),
('V_CLAIMS','PRIORITY','VARCHAR',FALSE,FALSE,17),('V_CLAIMS','SLA_BREACH_FLAG','BOOLEAN',FALSE,FALSE,18);

INSERT INTO CONFIG.INTERFACE_CONTRACTS (INTERFACE_NAME, COLUMN_NAME, DATA_TYPE, IS_REQUIRED, IS_PII, COLUMN_ORDER) VALUES
('V_INTERACTIONS','INTERACTION_ID','VARCHAR',TRUE,FALSE,1),('V_INTERACTIONS','CUSTOMER_ID','VARCHAR',TRUE,FALSE,2),
('V_INTERACTIONS','INTERACTION_DATE','TIMESTAMP_NTZ',FALSE,FALSE,3),('V_INTERACTIONS','CHANNEL','VARCHAR',FALSE,FALSE,4),
('V_INTERACTIONS','DIRECTION','VARCHAR',FALSE,FALSE,5),('V_INTERACTIONS','INTERACTION_TYPE','VARCHAR',FALSE,FALSE,6),
('V_INTERACTIONS','SUBJECT','VARCHAR',FALSE,FALSE,7),('V_INTERACTIONS','INTERACTION_SUMMARY','VARCHAR',FALSE,FALSE,8),
('V_INTERACTIONS','RESOLUTION_STATUS','VARCHAR',FALSE,FALSE,9),('V_INTERACTIONS','AGENT_ID','VARCHAR',FALSE,FALSE,10),
('V_INTERACTIONS','HANDLE_TIME_SECONDS','NUMBER',FALSE,FALSE,11),('V_INTERACTIONS','CSAT_SCORE','NUMBER',FALSE,FALSE,12),
('V_INTERACTIONS','RELATED_POLICY_ID','VARCHAR',FALSE,FALSE,13),('V_INTERACTIONS','RELATED_CLAIM_ID','VARCHAR',FALSE,FALSE,14);

INSERT INTO CONFIG.INTERFACE_CONTRACTS (INTERFACE_NAME, COLUMN_NAME, DATA_TYPE, IS_REQUIRED, IS_PII, COLUMN_ORDER) VALUES
('V_CALL_TRANSCRIPTS','TRANSCRIPT_ID','VARCHAR',TRUE,FALSE,1),('V_CALL_TRANSCRIPTS','CUSTOMER_ID','VARCHAR',TRUE,FALSE,2),
('V_CALL_TRANSCRIPTS','INTERACTION_ID','VARCHAR',FALSE,FALSE,3),('V_CALL_TRANSCRIPTS','TRANSCRIPT_TEXT','VARCHAR',FALSE,TRUE,4),
('V_CALL_TRANSCRIPTS','LANGUAGE_DETECTED','VARCHAR',FALSE,FALSE,5),('V_CALL_TRANSCRIPTS','CALL_TIMESTAMP','TIMESTAMP_NTZ',FALSE,FALSE,6);

INSERT INTO CONFIG.INTERFACE_CONTRACTS (INTERFACE_NAME, COLUMN_NAME, DATA_TYPE, IS_REQUIRED, IS_PII, COLUMN_ORDER) VALUES
('V_EMAILS','EMAIL_ID','VARCHAR',TRUE,FALSE,1),('V_EMAILS','CUSTOMER_ID','VARCHAR',TRUE,FALSE,2),
('V_EMAILS','EMAIL_DIRECTION','VARCHAR',FALSE,FALSE,3),('V_EMAILS','FROM_ADDRESS','VARCHAR',FALSE,TRUE,4),
('V_EMAILS','TO_ADDRESS','VARCHAR',FALSE,TRUE,5),('V_EMAILS','SUBJECT','VARCHAR',FALSE,FALSE,6),
('V_EMAILS','BODY_TEXT','VARCHAR',FALSE,FALSE,7),('V_EMAILS','EMAIL_TIMESTAMP','TIMESTAMP_NTZ',FALSE,FALSE,8);

-- Source table mappings
INSERT INTO CONFIG.SOURCE_TABLE_MAPPING (INTERFACE_NAME, SOURCE_DATABASE, SOURCE_SCHEMA, SOURCE_TABLE, JOIN_TYPE, JOIN_ORDER) VALUES
('V_CUSTOMERS','ACME_INSURANCE','DBO','TBL_CLIENTS','BASE',0),
('V_POLICIES','ACME_INSURANCE','DBO','TBL_POLICYMASTER','BASE',0),
('V_CLAIMS','ACME_INSURANCE','DBO','TBL_CLAIMREGISTER','BASE',0),
('V_INTERACTIONS','ACME_INSURANCE','DBO','TBL_INTERACTIONS','BASE',0),
('V_CALL_TRANSCRIPTS','ACME_INSURANCE','DBO','TBL_TRANSCRIPTS','BASE',0),
('V_EMAILS','ACME_INSURANCE','DBO','TBL_EMAILS','BASE',0);

-- Column mappings
INSERT INTO CONFIG.COLUMN_MAPPING (INTERFACE_NAME, INTERFACE_COLUMN, SOURCE_EXPRESSION) VALUES
('V_CUSTOMERS','CUSTOMER_ID','T0.CLIENTID::VARCHAR'),('V_CUSTOMERS','FIRST_NAME','T0.FNAME'),
('V_CUSTOMERS','LAST_NAME','T0.LNAME'),('V_CUSTOMERS','DATE_OF_BIRTH','T0.DOB'),
('V_CUSTOMERS','GENDER','T0.SEX'),('V_CUSTOMERS','PAN_NUMBER','T0.PANCARD'),
('V_CUSTOMERS','AADHAAR_NUMBER','T0.AADHAARNO'),('V_CUSTOMERS','MOBILE_NUMBER','T0.PHONENO'),
('V_CUSTOMERS','EMAIL_ADDRESS','T0.EMAILID'),('V_CUSTOMERS','ADDRESS_LINE_1','T0.ADDR'),
('V_CUSTOMERS','CITY','T0.CITYNAME'),('V_CUSTOMERS','STATE','T0.STATENAME'),
('V_CUSTOMERS','PINCODE','T0.ZIP'),('V_CUSTOMERS','CUSTOMER_SEGMENT','T0.TIER'),
('V_CUSTOMERS','ONBOARDING_DATE','T0.JOINDT'),('V_CUSTOMERS','KYC_STATUS','T0.KYCDONE'),
('V_CUSTOMERS','ANNUAL_INCOME','T0.SALARY'),('V_CUSTOMERS','OCCUPATION','T0.JOB'),
('V_CUSTOMERS','MARITAL_STATUS','T0.MARSTATUS'),('V_CUSTOMERS','NUMBER_OF_DEPENDENTS','T0.DEPENDENTS'),
('V_CUSTOMERS','IS_ACTIVE','IFF(T0.ACTIVEFLG = 1, TRUE, FALSE)'),
('V_POLICIES','POLICY_ID','T0.POLID'),('V_POLICIES','CUSTOMER_ID','T0.CLIENTID::VARCHAR'),
('V_POLICIES','POLICY_TYPE','T0.LOB'),('V_POLICIES','PRODUCT_NAME','T0.PRODNAME'),
('V_POLICIES','INCEPTION_DATE','T0.STARTDT'),('V_POLICIES','EXPIRY_DATE','T0.ENDDT'),
('V_POLICIES','SUM_INSURED','T0.SUMASSURED'),('V_POLICIES','ANNUAL_PREMIUM','T0.PREM'),
('V_POLICIES','PREMIUM_FREQUENCY','T0.PREMFREQ'),('V_POLICIES','POLICY_STATUS','T0.POLSTATUS'),
('V_POLICIES','UNDERWRITING_STATUS','T0.UWSTATUS'),('V_POLICIES','RISK_CATEGORY','T0.RISKCAT'),
('V_POLICIES','RISK_SCORE','T0.RISKPCT'),('V_POLICIES','AGENT_ID','T0.AGENTCODE'),
('V_POLICIES','BRANCH_CODE','T0.BRANCHID'),('V_POLICIES','IS_RENEWAL','IFF(T0.ISRENEW = 1, TRUE, FALSE)'),
('V_CLAIMS','CLAIM_ID','T0.CLAIMNO'),('V_CLAIMS','POLICY_ID','T0.POLID'),
('V_CLAIMS','CUSTOMER_ID','T0.CLIENTID::VARCHAR'),('V_CLAIMS','CLAIM_DATE','T0.CLAIMDT'),
('V_CLAIMS','CLAIM_TYPE','T0.CLAIMTYP'),('V_CLAIMS','CLAIM_CATEGORY','T0.CLAIMCAT'),
('V_CLAIMS','CLAIM_AMOUNT','T0.AMTCLAIMED'),('V_CLAIMS','APPROVED_AMOUNT','T0.AMTAPPROVED'),
('V_CLAIMS','CLAIM_STATUS','T0.STATUS'),('V_CLAIMS','CAUSE_OF_LOSS','T0.CAUSEOFLOSS'),
('V_CLAIMS','SETTLEMENT_DATE','T0.SETTLEDT'),('V_CLAIMS','DIAGNOSIS_DESCRIPTION','T0.DIAGDESC'),
('V_CLAIMS','TREATMENT_TYPE','T0.TREATTYPE'),('V_CLAIMS','FRAUD_FLAG','T0.FRAUDYN'),
('V_CLAIMS','FRAUD_SCORE','T0.FRAUDPCT'),('V_CLAIMS','CLAIM_DESCRIPTION','T0.CLAIMNOTES'),
('V_CLAIMS','PRIORITY','T0.PRIORITY'),('V_CLAIMS','SLA_BREACH_FLAG','IFF(T0.SLABREACH = 1, TRUE, FALSE)'),
('V_INTERACTIONS','INTERACTION_ID','T0.INTID'),('V_INTERACTIONS','CUSTOMER_ID','T0.CLIENTID::VARCHAR'),
('V_INTERACTIONS','INTERACTION_DATE','T0.INTDATE'),('V_INTERACTIONS','CHANNEL','T0.CHANNEL'),
('V_INTERACTIONS','DIRECTION','T0.DIRECTION'),('V_INTERACTIONS','INTERACTION_TYPE','T0.INTTYPE'),
('V_INTERACTIONS','SUBJECT','T0.SUBJECT'),('V_INTERACTIONS','INTERACTION_SUMMARY','T0.SUMMARY'),
('V_INTERACTIONS','RESOLUTION_STATUS','T0.RESOLUTION'),('V_INTERACTIONS','AGENT_ID','T0.AGENTCODE'),
('V_INTERACTIONS','HANDLE_TIME_SECONDS','T0.HANDLESECS'),('V_INTERACTIONS','CSAT_SCORE','T0.CSATSCORE'),
('V_INTERACTIONS','RELATED_POLICY_ID','T0.RELPOLID'),('V_INTERACTIONS','RELATED_CLAIM_ID','T0.RELCLMID'),
('V_CALL_TRANSCRIPTS','TRANSCRIPT_ID','T0.TRANSID'),('V_CALL_TRANSCRIPTS','CUSTOMER_ID','T0.CLIENTID::VARCHAR'),
('V_CALL_TRANSCRIPTS','INTERACTION_ID','T0.INTID'),('V_CALL_TRANSCRIPTS','TRANSCRIPT_TEXT','T0.TRANSTEXT'),
('V_CALL_TRANSCRIPTS','LANGUAGE_DETECTED','T0.LANG'),('V_CALL_TRANSCRIPTS','CALL_TIMESTAMP','T0.CALLTS'),
('V_EMAILS','EMAIL_ID','T0.EMAILID'),('V_EMAILS','CUSTOMER_ID','T0.CLIENTID::VARCHAR'),
('V_EMAILS','EMAIL_DIRECTION','T0.DIRECTION'),('V_EMAILS','FROM_ADDRESS','T0.FROMADDR'),
('V_EMAILS','TO_ADDRESS','T0.TOADDR'),('V_EMAILS','SUBJECT','T0.SUBJECT'),
('V_EMAILS','BODY_TEXT','T0.BODYTEXT'),('V_EMAILS','EMAIL_TIMESTAMP','T0.EMAILTS');

-- Value mappings
INSERT INTO CONFIG.VALUE_MAPPING (INTERFACE_NAME, INTERFACE_COLUMN, SOURCE_VALUE, TARGET_VALUE, IS_DEFAULT) VALUES
('V_CUSTOMERS','GENDER','M','Male',FALSE),('V_CUSTOMERS','GENDER','F','Female',FALSE),('V_CUSTOMERS','GENDER','O','Other',TRUE),
('V_CUSTOMERS','CUSTOMER_SEGMENT','P','PLATINUM',FALSE),('V_CUSTOMERS','CUSTOMER_SEGMENT','G','GOLD',FALSE),
('V_CUSTOMERS','CUSTOMER_SEGMENT','S','SILVER',FALSE),('V_CUSTOMERS','CUSTOMER_SEGMENT','B','BRONZE',FALSE),
('V_CUSTOMERS','KYC_STATUS','Y','VERIFIED',FALSE),('V_CUSTOMERS','KYC_STATUS','N','PENDING',FALSE),('V_CUSTOMERS','KYC_STATUS','E','EXPIRED',FALSE),
('V_CUSTOMERS','MARITAL_STATUS','M','MARRIED',FALSE),('V_CUSTOMERS','MARITAL_STATUS','S','SINGLE',FALSE),
('V_CUSTOMERS','MARITAL_STATUS','D','DIVORCED',FALSE),('V_CUSTOMERS','MARITAL_STATUS','W','WIDOWED',FALSE),
('V_POLICIES','POLICY_TYPE','LI','LIFE',FALSE),('V_POLICIES','POLICY_TYPE','HE','HEALTH',FALSE),
('V_POLICIES','POLICY_TYPE','MO','MOTOR',FALSE),('V_POLICIES','POLICY_TYPE','HO','HOME',FALSE),('V_POLICIES','POLICY_TYPE','TR','TRAVEL',FALSE),
('V_POLICIES','POLICY_STATUS','ACT','ACTIVE',FALSE),('V_POLICIES','POLICY_STATUS','LAP','LAPSED',FALSE),
('V_POLICIES','POLICY_STATUS','CAN','CANCELLED',FALSE),('V_POLICIES','POLICY_STATUS','EXP','EXPIRED',FALSE),('V_POLICIES','POLICY_STATUS','SUR','SURRENDERED',FALSE),
('V_POLICIES','UNDERWRITING_STATUS','APP','APPROVED',FALSE),('V_POLICIES','UNDERWRITING_STATUS','PEN','PENDING',FALSE),('V_POLICIES','UNDERWRITING_STATUS','REJ','REJECTED',FALSE),
('V_POLICIES','PREMIUM_FREQUENCY','M','MONTHLY',FALSE),('V_POLICIES','PREMIUM_FREQUENCY','Q','QUARTERLY',FALSE),
('V_POLICIES','PREMIUM_FREQUENCY','H','SEMI_ANNUAL',FALSE),('V_POLICIES','PREMIUM_FREQUENCY','A','ANNUAL',FALSE),
('V_POLICIES','RISK_CATEGORY','1','LOW',FALSE),('V_POLICIES','RISK_CATEGORY','2','MEDIUM',FALSE),
('V_POLICIES','RISK_CATEGORY','3','HIGH',FALSE),('V_POLICIES','RISK_CATEGORY','4','VERY_HIGH',FALSE),
('V_CLAIMS','CLAIM_TYPE','CSH','CASHLESS',FALSE),('V_CLAIMS','CLAIM_TYPE','RMB','REIMBURSEMENT',FALSE),
('V_CLAIMS','CLAIM_TYPE','DTH','DEATH',FALSE),('V_CLAIMS','CLAIM_TYPE','ACC','ACCIDENT',FALSE),('V_CLAIMS','CLAIM_TYPE','THF','THEFT',FALSE),
('V_CLAIMS','CLAIM_CATEGORY','HE','HEALTH',FALSE),('V_CLAIMS','CLAIM_CATEGORY','MO','MOTOR',FALSE),
('V_CLAIMS','CLAIM_CATEGORY','LI','LIFE',FALSE),('V_CLAIMS','CLAIM_CATEGORY','PR','PROPERTY',FALSE),
('V_CLAIMS','CLAIM_STATUS','REP','REPORTED',FALSE),('V_CLAIMS','CLAIM_STATUS','URV','UNDER_REVIEW',FALSE),
('V_CLAIMS','CLAIM_STATUS','APR','APPROVED',FALSE),('V_CLAIMS','CLAIM_STATUS','REJ','REJECTED',FALSE),
('V_CLAIMS','CLAIM_STATUS','SET','SETTLED',FALSE),('V_CLAIMS','CLAIM_STATUS','CLS','CLOSED',FALSE),
('V_CLAIMS','FRAUD_FLAG','Y','Y',FALSE),('V_CLAIMS','FRAUD_FLAG','N','N',FALSE),('V_CLAIMS','FRAUD_FLAG','S','SUSPECT',FALSE),
('V_CLAIMS','PRIORITY','1','LOW',FALSE),('V_CLAIMS','PRIORITY','2','MEDIUM',FALSE),
('V_CLAIMS','PRIORITY','3','HIGH',FALSE),('V_CLAIMS','PRIORITY','4','CRITICAL',FALSE);

-- Onboarding status
INSERT INTO CONFIG.ONBOARDING_STATUS (INTERFACE_NAME) VALUES
('V_CUSTOMERS'),('V_POLICIES'),('V_CLAIMS'),('V_INTERACTIONS'),('V_CALL_TRANSCRIPTS'),('V_EMAILS');


-- =============================================================================
-- PART 11: GENERATE VIEWS (must run AFTER data is loaded in ACME tables)
-- =============================================================================

CALL CONFIG.GENERATE_INTERFACE_VIEW('V_CUSTOMERS');
CALL CONFIG.GENERATE_INTERFACE_VIEW('V_POLICIES');
CALL CONFIG.GENERATE_INTERFACE_VIEW('V_CLAIMS');
CALL CONFIG.GENERATE_INTERFACE_VIEW('V_INTERACTIONS');
CALL CONFIG.GENERATE_INTERFACE_VIEW('V_CALL_TRANSCRIPTS');
CALL CONFIG.GENERATE_INTERFACE_VIEW('V_EMAILS');


-- =============================================================================
-- PART 12: DYNAMIC TABLE (must run AFTER views are created)
-- =============================================================================

CREATE OR REPLACE DYNAMIC TABLE ANALYTICS.DT_CUSTOMER_360
    TARGET_LAG = '30 minutes' WAREHOUSE = WH_INSURE360_APP
AS
WITH policy_agg AS (
    SELECT CUSTOMER_ID,
        COUNT(DISTINCT POLICY_ID) AS TOTAL_POLICIES,
        COUNT(DISTINCT CASE WHEN POLICY_STATUS = 'ACTIVE' THEN POLICY_ID END) AS ACTIVE_POLICIES,
        COUNT(DISTINCT CASE WHEN POLICY_STATUS = 'LAPSED' THEN POLICY_ID END) AS LAPSED_POLICIES,
        ARRAY_AGG(DISTINCT POLICY_TYPE) AS POLICY_TYPES,
        COALESCE(SUM(SUM_INSURED), 0) AS TOTAL_SUM_INSURED,
        COALESCE(SUM(CASE WHEN POLICY_STATUS = 'ACTIVE' THEN ANNUAL_PREMIUM ELSE 0 END), 0) AS TOTAL_ANNUAL_PREMIUM,
        MIN(CASE WHEN POLICY_STATUS = 'ACTIVE' AND EXPIRY_DATE > CURRENT_DATE() THEN EXPIRY_DATE END) AS NEXT_RENEWAL_DATE
    FROM INSURE360_APP.INTERFACE.V_POLICIES GROUP BY CUSTOMER_ID
),
claims_agg AS (
    SELECT CUSTOMER_ID,
        COUNT(DISTINCT CLAIM_ID) AS TOTAL_CLAIMS,
        COUNT(DISTINCT CASE WHEN CLAIM_STATUS NOT IN ('SETTLED','CLOSED','REJECTED') THEN CLAIM_ID END) AS OPEN_CLAIMS,
        COALESCE(SUM(CLAIM_AMOUNT), 0) AS TOTAL_CLAIM_AMOUNT,
        COALESCE(SUM(APPROVED_AMOUNT), 0) AS TOTAL_APPROVED_AMOUNT,
        MAX(CASE WHEN FRAUD_FLAG IN ('Y','SUSPECT') THEN TRUE ELSE FALSE END) AS HAS_FRAUD_FLAG
    FROM INSURE360_APP.INTERFACE.V_CLAIMS GROUP BY CUSTOMER_ID
)
SELECT c.CUSTOMER_ID, CONCAT(c.FIRST_NAME, ' ', c.LAST_NAME) AS CUSTOMER_NAME,
    DATEDIFF('YEAR', c.DATE_OF_BIRTH, CURRENT_DATE()) AS AGE, c.GENDER, c.CITY, c.STATE,
    c.CUSTOMER_SEGMENT, DATEDIFF('MONTH', c.ONBOARDING_DATE, CURRENT_DATE()) AS CUSTOMER_TENURE_MONTHS,
    c.PREFERRED_CHANNEL,
    COALESCE(p.TOTAL_POLICIES, 0) AS TOTAL_POLICIES, COALESCE(p.ACTIVE_POLICIES, 0) AS ACTIVE_POLICIES,
    COALESCE(p.LAPSED_POLICIES, 0) AS LAPSED_POLICIES, p.POLICY_TYPES,
    COALESCE(p.TOTAL_SUM_INSURED, 0) AS TOTAL_SUM_INSURED, COALESCE(p.TOTAL_ANNUAL_PREMIUM, 0) AS TOTAL_ANNUAL_PREMIUM,
    p.NEXT_RENEWAL_DATE, DATEDIFF('DAY', CURRENT_DATE(), p.NEXT_RENEWAL_DATE) AS DAYS_TO_RENEWAL,
    COALESCE(cl.TOTAL_CLAIMS, 0) AS TOTAL_CLAIMS, COALESCE(cl.OPEN_CLAIMS, 0) AS OPEN_CLAIMS,
    COALESCE(cl.TOTAL_CLAIM_AMOUNT, 0) AS TOTAL_CLAIM_AMOUNT, COALESCE(cl.TOTAL_APPROVED_AMOUNT, 0) AS TOTAL_APPROVED_AMOUNT,
    COALESCE(cl.HAS_FRAUD_FLAG, FALSE) AS HAS_FRAUD_FLAG, CURRENT_TIMESTAMP() AS LAST_REFRESHED
FROM INSURE360_APP.INTERFACE.V_CUSTOMERS c
LEFT JOIN policy_agg p ON c.CUSTOMER_ID = p.CUSTOMER_ID
LEFT JOIN claims_agg cl ON c.CUSTOMER_ID = cl.CUSTOMER_ID
WHERE c.IS_ACTIVE = TRUE;


-- =============================================================================
-- PART 13: FINAL GRANTS
-- =============================================================================

GRANT SELECT ON ALL TABLES IN SCHEMA INSURE360_APP.AI TO ROLE INSURE360_ADMIN;
GRANT SELECT ON ALL TABLES IN SCHEMA INSURE360_APP.ANALYTICS TO ROLE INSURE360_ADMIN;
GRANT SELECT ON ALL TABLES IN SCHEMA INSURE360_APP.RECOMMENDATIONS TO ROLE INSURE360_ADMIN;
GRANT ALL ON TABLE INSURE360_APP.RECOMMENDATIONS.TICKETS TO ROLE INSURE360_ADMIN;
GRANT ALL ON TABLE INSURE360_APP.RECOMMENDATIONS.NEXT_BEST_ACTION TO ROLE INSURE360_ADMIN;
GRANT USAGE ON SEQUENCE INSURE360_APP.RECOMMENDATIONS.SEQ_TICKET_ID TO ROLE INSURE360_ADMIN;
GRANT SELECT ON ALL TABLES IN SCHEMA INSURE360_APP.CONFIG TO ROLE INSURE360_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE INSURE360_APP.CONFIG.ROLE_PAGE_ACCESS TO ROLE INSURE360_ADMIN;

GRANT SELECT ON ALL TABLES IN SCHEMA INSURE360_APP.INTERFACE TO ROLE INSURE360_SALES_ADVISOR;
GRANT SELECT ON ALL TABLES IN SCHEMA INSURE360_APP.INTERFACE TO ROLE INSURE360_CLAIMS_PROCESSOR;
GRANT SELECT ON ALL TABLES IN SCHEMA INSURE360_APP.INTERFACE TO ROLE INSURE360_UNDERWRITER;
GRANT SELECT ON ALL TABLES IN SCHEMA INSURE360_APP.INTERFACE TO ROLE INSURE360_RETENTION_MGR;
GRANT SELECT ON ALL TABLES IN SCHEMA INSURE360_APP.INTERFACE TO ROLE INSURE360_CC_MANAGER;
GRANT SELECT ON ALL TABLES IN SCHEMA INSURE360_APP.INTERFACE TO ROLE INSURE360_VIEWER;

GRANT SELECT ON ALL TABLES IN SCHEMA INSURE360_APP.ANALYTICS TO ROLE INSURE360_SALES_ADVISOR;
GRANT SELECT ON ALL TABLES IN SCHEMA INSURE360_APP.ANALYTICS TO ROLE INSURE360_CLAIMS_PROCESSOR;
GRANT SELECT ON ALL TABLES IN SCHEMA INSURE360_APP.ANALYTICS TO ROLE INSURE360_UNDERWRITER;
GRANT SELECT ON ALL TABLES IN SCHEMA INSURE360_APP.ANALYTICS TO ROLE INSURE360_RETENTION_MGR;
GRANT SELECT ON ALL TABLES IN SCHEMA INSURE360_APP.ANALYTICS TO ROLE INSURE360_CC_MANAGER;
GRANT SELECT ON ALL TABLES IN SCHEMA INSURE360_APP.ANALYTICS TO ROLE INSURE360_VIEWER;

GRANT SELECT ON ALL TABLES IN SCHEMA INSURE360_APP.AI TO ROLE INSURE360_SALES_ADVISOR;
GRANT SELECT ON ALL TABLES IN SCHEMA INSURE360_APP.AI TO ROLE INSURE360_CLAIMS_PROCESSOR;
GRANT SELECT ON ALL TABLES IN SCHEMA INSURE360_APP.AI TO ROLE INSURE360_UNDERWRITER;
GRANT SELECT ON ALL TABLES IN SCHEMA INSURE360_APP.AI TO ROLE INSURE360_RETENTION_MGR;
GRANT SELECT ON ALL TABLES IN SCHEMA INSURE360_APP.AI TO ROLE INSURE360_CC_MANAGER;

GRANT SELECT ON ALL TABLES IN SCHEMA INSURE360_APP.RECOMMENDATIONS TO ROLE INSURE360_SALES_ADVISOR;
GRANT SELECT ON ALL TABLES IN SCHEMA INSURE360_APP.RECOMMENDATIONS TO ROLE INSURE360_CLAIMS_PROCESSOR;
GRANT SELECT ON ALL TABLES IN SCHEMA INSURE360_APP.RECOMMENDATIONS TO ROLE INSURE360_RETENTION_MGR;

-- Future grants
GRANT SELECT ON FUTURE TABLES IN SCHEMA INSURE360_APP.INTERFACE TO ROLE INSURE360_SALES_ADVISOR;
GRANT SELECT ON FUTURE TABLES IN SCHEMA INSURE360_APP.ANALYTICS TO ROLE INSURE360_SALES_ADVISOR;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA INSURE360_APP.INTERFACE TO ROLE INSURE360_SALES_ADVISOR;

-- Force DT refresh
ALTER DYNAMIC TABLE INSURE360_APP.ANALYTICS.DT_CUSTOMER_360 REFRESH;

SELECT 'DEPLOYMENT COMPLETE! Load CSV data into ACME tables, then deploy the Streamlit app.' AS STATUS;
